### ISSUE TITLE
Does not look good on 16:10 screens

### ISSUE THREAD

**Issue by pythonian23** [VandalByte/darkmatter-grub2-theme#30]
The theme is great and I wanted to use it, but it appears somewhat stretched and pixelated on my 16:10 screen. Could you make it support non-standard screen sizes? Thanks!

**Comment by VandalByte** [comment]
Hey @pythonian23, yeah that's probably because the theme background is 16:9 which works fine for 1920x1080 & 1366×768. And sure I will add it in the future along with all the planned future updates

**Comment by VandalByte** [comment]
Until then, I've created a sort of temporary background for you. All the rest of the stuff should if the fonts appear fuzzy it's cause of how grub renders it. so let me know if it works for you 👍

![linux](https://user-images.githubusercontent.com/86826719/173475450-f84dc65e-45ee-4573-ab79-753d606514ec.png)
