### ISSUE TITLE
Not working on Fedora 37

### ISSUE THREAD

**Issue by ovib** [VandalByte/darkmatter-grub2-theme#35]

**Comment by VandalByte** [comment]
@ovib have you tried the method mentioned [here](https://github.com/VandalByte/grub-tweaks#-fix-for-grub-theme-not-showing-up--fedora-ubuntu-)?

**Comment by ovib** [comment]
No, but I've check now and the lines were correct. 

I've tried to reinstall and I notices that I get the error: `/bin/sh: line 1: grub-mkconfig: command not found`
![Screenshot from 2022-12-04 12-02-13](https://user-images.githubusercontent.com/38936570/205487066-04331fe9-6d47-4ee1-bd82-cd8c818dc650.png)

**Comment by VandalByte** [comment]
@ovib 
Oh yeah you can just ignore that error, the theme should be installed correctly by now, I added that part just to show some extra info to Kali Linux users
