### ISSUE TITLE
[Theme request] Add Athena OS

### ISSUE THREAD

**Issue by D3vil0p3r** [VandalByte/darkmatter-grub2-theme#36]
Hello @VandalByte 
I'm not sure if GitHub or GitLab repository could be the right place for opening issue tickets for darkmatter-grub2-theme.

Is there a chance to implement the following? https://gitlab.com/VandalByte/darkmatter-grub-theme/-/issues/9

Thank you for this awesome work.

**Comment by VandalByte** [comment]
@D3vil0p3r Added :)
