### ISSUE TITLE
Include base theming assets?

### ISSUE THREAD

**Issue by KaleiAlma** [VandalByte/darkmatter-grub2-theme#39]
I was wondering if you could include the base assets (mostly the background image and maybe colorless transparent versions of the bars and the line at the top) so that anyone could make a new variant of the theme if they wanted to, instead of relying on you (and it'd allow you to take a bit more of a break too ;) ). It's not *too* hard to change the image being referred to imo, especially if they have something like Grub Customizer installed.

**Comment by VandalByte** [comment]
@KaleiAlma 
Yeah that actually is a nice idea, let me see what I can do...
PS: I need that break lol
