### ISSUE TITLE
Windows  icons not showing in the list

### ISSUE THREAD

**Issue by gaetan1903** [VandalByte/darkmatter-grub2-theme#40]
I'm using Fedora and in the icon list Windows doesn't seem to have any icons,

OS name is Windows Boot Manager, I rename it with Windows but not working yet

**Comment by VandalByte** [comment]
@gaetan1903 

Check this out, so basically find where this line is in one of those .cfg files
```
menuentry 'Windows Boot Manager' {
```
and change it to this
```
menuentry 'Windows Boot Manager' --class windows {
```
here `windows` is the icon name

**Comment by gaetan1903** [comment]
Thank you @VandalByte  for your answer, 

i find this line in grub.cfg file and it's already like you say, 
```
menuentry 'Windows Boot Manager' --class windows {
```

However in your icon  filelist, there is no windows.png but only windows10.png and windows11.png , 

so i change it to 
```
menuentry 'Windows Boot Manager' --class windows11 {
```

and it works now, 

Thanks again

**Comment by gaetan1903** [comment]
The solution might be to also have a windows.png file
